name: engine-test
on: 
  push

jobs:
  run-engine-tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: run script
      run: |
         chmod +x ./test-script.sh
         ./test-script.sh
