[package]
name = "TrueChess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-random="0.1.17"
libm="0.2.8"

[profile.release]
lto = true
